### ISSUE TITLE
Adding Dynamic Routing For Chat and Video Calls 

### ISSUE THREAD

**Issue by AkshayPratapSingh09** [AkshayPratapSingh09/Video-Calling-App#5]
Issue : Adding Dynamic Routing in App.js For Chat and Video Calls and make them route according to their respective rooms.

**Comment by Priyankaa2503** [comment]
Hello, i would like to work on this issue. Could you assign it to me?

**Comment by Priyankaa2503** [comment]
I have added dynamic routing for chat as for video call as socket functionality has not been implemented yet.
Is anything else required ?
<img width="1134" alt="Screenshot 2023-10-07 at 3 37 12 PM" src="https://github.com/AkshayPratapSingh09/Video-Calling-App/assets/111295843/50b18c5f-87c6-40f8-90f8-5fc713f864d4">
